package com.kauth.domain.service

import com.kauth.domain.model.AccessType
import com.kauth.domain.model.ApplicationId
import com.kauth.domain.model.AuditEvent
import com.kauth.domain.model.AuditEventType
import com.kauth.domain.model.BackupExportV1
import com.kauth.domain.model.Group
import com.kauth.domain.model.GroupBackup
import com.kauth.domain.model.GroupId
import com.kauth.domain.model.IdentityProvider
import com.kauth.domain.model.RequiredAction
import com.kauth.domain.model.Role
import com.kauth.domain.model.RoleId
import com.kauth.domain.model.RoleScope
import com.kauth.domain.model.SecurityConfig
import com.kauth.domain.model.SocialProvider
import com.kauth.domain.model.TenantClaimMapper
import com.kauth.domain.model.TenantKey
import com.kauth.domain.model.TenantTheme
import com.kauth.domain.model.User
import com.kauth.domain.model.UserAttribute
import com.kauth.domain.model.UserId
import com.kauth.domain.port.ApplicationRepository
import com.kauth.domain.port.AuditLogPort
import com.kauth.domain.port.GroupRepository
import com.kauth.domain.port.IdentityProviderRepository
import com.kauth.domain.port.PortalConfigRepository
import com.kauth.domain.port.RoleRepository
import com.kauth.domain.port.TenantClaimMapperRepository
import com.kauth.domain.port.TenantEmailBrandingRepository
import com.kauth.domain.port.TenantKeyRepository
import com.kauth.domain.port.TenantRepository
import com.kauth.domain.port.ThemeRepository
import com.kauth.domain.port.TransactionRunner
import com.kauth.domain.port.UserAttributeRepository
import com.kauth.domain.port.UserRepository
import java.time.Instant

/**
 * Domain service that materialises a [BackupExportV1] as a fresh tenant on this
 * deployment. Always creates a NEW tenant — in-place restore is deferred to v1.10.x.
 *
 * **Atomicity.** All writes happen inside a single [TransactionRunner.runInTransaction]
 * block. Any exception triggers a full rollback; partial imports are impossible.
 *
 * **ID remapping.** The export carries no database IDs; entities reference each
 * other by natural keys (slug, username, role name, group path, clientId). The
 * importer builds in-memory name→ID lookups as it inserts each row, then resolves
 * cross-entity references in dependency order:
 *
 *   1. Tenant (slug, settings, security config, theme, portal config)
 *   2. Signing keys — fresh RSA pair generated by the host caller unless the
 *      export opted into [BackupExportV1.signingKeys]; importer just persists
 *      whatever it's given (the route layer decides which set to pass)
 *   3. Applications (need tenant id; provide clientId → newAppPk lookup)
 *   4. Roles, two passes:
 *        a. Insert all roles (no composite links yet)
 *        b. Apply parent→child mappings using the now-complete name→id lookup
 *   5. Groups, topologically sorted by parent path so parents exist before children
 *   6. Group→role assignments
 *   7. Users
 *   8. User attributes
 *   9. User→role assignments
 *  10. User→group memberships
 *  11. Claim mappers
 *  12. Identity providers (clientSecret intentionally left blank, enabled=false —
 *      operator re-enters secret in admin UI before re-enabling)
 *  13. Audit log (append-only)
 */
class BackupImporterService(
    private val tenantRepository: TenantRepository,
    private val userRepository: UserRepository,
    private val applicationRepository: ApplicationRepository,
    private val roleRepository: RoleRepository,
    private val groupRepository: GroupRepository,
    private val claimMapperRepository: TenantClaimMapperRepository,
    private val identityProviderRepository: IdentityProviderRepository,
    private val tenantKeyRepository: TenantKeyRepository,
    private val themeRepository: ThemeRepository,
    private val portalConfigRepository: PortalConfigRepository,
    private val userAttributeRepository: UserAttributeRepository,
    private val emailBrandingRepository: TenantEmailBrandingRepository,
    private val auditLogPort: AuditLogPort?,
    private val transactionRunner: TransactionRunner,
) {
    /**
     * @param export decoded payload to import
     * @param newSlug destination tenant slug — must not already exist
     * @param currentSchemaVersion Flyway head V-number on the destination
     */
    fun import(
        export: BackupExportV1,
        newSlug: String,
        currentSchemaVersion: Int,
    ): BackupResult<ImportSummary> {
        when (val compat = BackupCompatibilityMatrix.check(export.schemaVersion, currentSchemaVersion)) {
            is CompatibilityResult.RejectBreaking ->
                return BackupResult.Failure(
                    BackupError.SchemaTooNew(compat.exportSchemaVersion, compat.currentSchemaVersion),
                )
            else -> Unit
        }

        if (tenantRepository.existsBySlug(newSlug)) {
            return BackupResult.Failure(BackupError.SlugConflict(newSlug))
        }

        return try {
            val summary = transactionRunner.runInTransaction { performImport(export, newSlug) }
            BackupResult.Success(summary)
        } catch (e: IllegalStateException) {
            BackupResult.Failure(BackupError.InvalidPayload(e.message ?: "invalid backup payload"))
        }
    }

    private fun performImport(
        export: BackupExportV1,
        newSlug: String,
    ): ImportSummary {
        val tb = export.tenant

        val createdTenant =
            tenantRepository.create(
                slug = newSlug,
                displayName = tb.displayName,
                issuerUrl = tb.issuerUrl,
            )

        val fullTenant =
            createdTenant.copy(
                tokenExpirySeconds = tb.tokenExpirySeconds,
                refreshTokenExpirySeconds = tb.refreshTokenExpirySeconds,
                registrationEnabled = tb.registrationEnabled,
                emailVerificationRequired = tb.emailVerificationRequired,
                maxConcurrentSessions = tb.maxConcurrentSessions,
                securityConfig =
                    with(tb.securityConfig) {
                        SecurityConfig(
                            passwordMinLength = passwordMinLength,
                            passwordRequireSpecial = passwordRequireSpecial,
                            passwordRequireUppercase = passwordRequireUppercase,
                            passwordRequireNumber = passwordRequireNumber,
                            passwordHistoryCount = passwordHistoryCount,
                            passwordMaxAgeDays = passwordMaxAgeDays,
                            passwordBlacklistEnabled = passwordBlacklistEnabled,
                            mfaPolicy = mfaPolicy,
                            lockoutMaxAttempts = lockoutMaxAttempts,
                            lockoutDurationMinutes = lockoutDurationMinutes,
                            corsAllowCredentials = corsAllowCredentials,
                            hibpCheckEnabled = hibpCheckEnabled,
                            magicLinkEnabled = magicLinkEnabled,
                            magicLinkTokenTtlMinutes = magicLinkTokenTtlMinutes,
                            passwordLoginEnabled = passwordLoginEnabled,
                            emailOtpSignupEnabled = emailOtpSignupEnabled,
                            emailOtpLockoutThreshold = emailOtpLockoutThreshold,
                            emailOtpLoginEnabled = emailOtpLoginEnabled,
                        )
                    },
                smtpHost = tb.smtp.host,
                smtpPort = tb.smtp.port,
                smtpUsername = tb.smtp.username,
                smtpPassword = null,
                smtpFromAddress = tb.smtp.fromAddress,
                smtpFromName = tb.smtp.fromName,
                smtpTlsEnabled = tb.smtp.tlsEnabled,
                smtpEnabled = false,
            )
        tenantRepository.update(fullTenant)

        themeRepository.upsert(
            createdTenant.id,
            with(tb.theme) {
                TenantTheme(
                    accentColor = accentColor,
                    accentHoverColor = accentHoverColor,
                    accentForeground = accentForeground,
                    bgDeep = bgDeep,
                    surface = surface,
                    bgInput = bgInput,
                    borderColor = borderColor,
                    borderRadius = borderRadius,
                    textPrimary = textPrimary,
                    textMuted = textMuted,
                    fontFamily = fontFamily,
                    logoUrl = logoUrl,
                    faviconUrl = faviconUrl,
                    defaultLocale = defaultLocale,
                )
            },
        )

        portalConfigRepository.upsert(
            createdTenant.id,
            com.kauth.domain.model.PortalConfig(
                layout =
                    runCatching {
                        com.kauth.domain.model.PortalLayout
                            .valueOf(tb.portalConfig.layout)
                    }.getOrDefault(com.kauth.domain.model.PortalLayout.SIDEBAR),
            ),
        )

        tb.emailBranding?.let { eb ->
            emailBrandingRepository.upsert(
                com.kauth.domain.model.TenantEmailBranding(
                    tenantId = createdTenant.id,
                    brandName = eb.brandName,
                    brandColorHex = eb.brandColorHex,
                    brandLogoUrl = eb.brandLogoUrl,
                    supportEmail = eb.supportEmail,
                    fromDisplayName = eb.fromDisplayName,
                ),
            )
        }

        export.signingKeys?.forEach { keyBackup ->
            tenantKeyRepository.save(
                TenantKey(
                    id = null,
                    tenantId = createdTenant.id,
                    keyId = keyBackup.keyId,
                    algorithm = keyBackup.algorithm,
                    publicKeyPem = keyBackup.publicKeyPem,
                    privateKeyPem = keyBackup.privateKeyPem,
                    enabled = keyBackup.enabled,
                    active = keyBackup.active,
                    createdAt = keyBackup.createdAt?.let(Instant::ofEpochSecond),
                ),
            )
        }

        val appPkByClientId: MutableMap<String, ApplicationId> = mutableMapOf()
        export.applications.forEach { ab ->
            val saved =
                applicationRepository.create(
                    tenantId = createdTenant.id,
                    clientId = ab.clientId,
                    name = ab.name,
                    description = ab.description,
                    accessType = AccessType.fromValue(ab.accessType).value,
                    redirectUris = ab.redirectUris,
                )
            val finalApp =
                if (!ab.enabled) {
                    applicationRepository.setEnabled(saved.id, false)
                    saved.copy(enabled = false)
                } else {
                    saved
                }
            appPkByClientId[finalApp.clientId] = finalApp.id
        }

        val rolePkByName: MutableMap<RoleScopedKey, RoleId> = mutableMapOf()
        export.roles.forEach { rb ->
            val scope = RoleScope.fromValue(rb.scope)
            val clientPk =
                rb.clientId?.let { appPkByClientId[it] }
                    ?: if (scope == RoleScope.CLIENT) {
                        error(
                            "Role '${rb.name}' is CLIENT-scoped but referenced clientId '${rb.clientId}' was not exported",
                        )
                    } else {
                        null
                    }
            val saved =
                roleRepository.save(
                    Role(
                        id = null,
                        tenantId = createdTenant.id,
                        name = rb.name,
                        description = rb.description,
                        scope = scope,
                        clientId = clientPk,
                    ),
                )
            val savedId = saved.id ?: error("RoleRepository.save returned a role with null id for '${rb.name}'")
            rolePkByName[RoleScopedKey(rb.name, scope, rb.clientId)] = savedId
        }

        export.roles.forEach { rb ->
            if (rb.childRoleNames.isEmpty()) return@forEach
            val parentScope = RoleScope.fromValue(rb.scope)
            val parentId =
                rolePkByName[RoleScopedKey(rb.name, parentScope, rb.clientId)]
                    ?: error("Parent role '${rb.name}' missing from name→id lookup")
            rb.childRoleNames.forEach { childName ->
                val childId =
                    rolePkByName.entries.firstOrNull { it.key.name == childName }?.value
                        ?: error("Child role '$childName' (parent '${rb.name}') was not in this export")
                roleRepository.addChildRole(parentId, childId)
            }
        }

        val groupPkByPath: MutableMap<String, GroupId> = mutableMapOf()
        topologicalGroups(export.groups).forEach { gb ->
            val parentPk = gb.parentGroupPath?.let { groupPkByPath[it] }
            if (gb.parentGroupPath != null && parentPk == null) {
                error("Group '${gb.name}' references missing parent path '${gb.parentGroupPath}'")
            }
            val saved =
                groupRepository.save(
                    Group(
                        id = null,
                        tenantId = createdTenant.id,
                        name = gb.name,
                        description = gb.description,
                        parentGroupId = parentPk,
                        attributes = gb.attributes,
                    ),
                )
            val savedId = saved.id ?: error("GroupRepository.save returned a group with null id for '${gb.name}'")
            val ownPath = if (gb.parentGroupPath == null) gb.name else "${gb.parentGroupPath}/${gb.name}"
            groupPkByPath[ownPath] = savedId

            gb.roleNames.forEach { roleName ->
                val roleId = lookupRoleId(roleName, rolePkByName)
                groupRepository.assignRoleToGroup(savedId, roleId)
            }
        }

        val userPkByUsername: MutableMap<String, UserId> = mutableMapOf()
        export.users.forEach { ub ->
            val saved =
                userRepository.save(
                    User(
                        id = null,
                        tenantId = createdTenant.id,
                        username = ub.username,
                        email = ub.email,
                        fullName = ub.fullName,
                        passwordHash = ub.passwordHash,
                        emailVerified = ub.emailVerified,
                        enabled = ub.enabled,
                        requiredActions = ub.requiredActions.mapNotNull { parseRequiredAction(it) }.toSet(),
                        lastPasswordChangeAt = ub.lastPasswordChangeAt?.let(Instant::ofEpochSecond),
                        mfaEnabled = false,
                        createdAt = ub.createdAt?.let(Instant::ofEpochSecond),
                    ),
                )
            val savedId = saved.id ?: error("UserRepository.save returned a user with null id for '${ub.username}'")
            userPkByUsername[ub.username] = savedId

            ub.customAttributes.forEach { (key, value) ->
                userAttributeRepository.upsert(
                    UserAttribute(
                        userId = savedId,
                        tenantId = createdTenant.id,
                        key = key,
                        value = value,
                        updatedAt = Instant.now(),
                    ),
                )
            }

            ub.roleNames.forEach { roleName ->
                roleRepository.assignRoleToUser(savedId, lookupRoleId(roleName, rolePkByName))
            }

            ub.groupPaths.forEach { path ->
                val groupId =
                    groupPkByPath[path]
                        ?: error("User '${ub.username}' references missing group path '$path'")
                groupRepository.addUserToGroup(savedId, groupId)
            }
        }

        export.claimMappers.forEach { cm ->
            claimMapperRepository.upsert(
                TenantClaimMapper(
                    tenantId = createdTenant.id,
                    attributeKey = cm.attributeKey,
                    claimName = cm.claimName,
                    includeInAccess = cm.includeInAccess,
                    includeInId = cm.includeInId,
                ),
            )
        }

        export.socialProviders.forEach { sp ->
            val provider = SocialProvider.fromValueOrNull(sp.provider) ?: return@forEach
            identityProviderRepository.save(
                IdentityProvider(
                    id = null,
                    tenantId = createdTenant.id,
                    provider = provider,
                    clientId = sp.clientId,
                    clientSecret = "",
                    enabled = false,
                ),
            )
        }

        export.auditLog?.forEach { ev ->
            auditLogPort?.record(
                AuditEvent(
                    tenantId = createdTenant.id,
                    userId = ev.username?.let { userPkByUsername[it] },
                    clientId = ev.clientId?.let { appPkByClientId[it] },
                    eventType =
                        runCatching { AuditEventType.valueOf(ev.eventType) }
                            .getOrNull() ?: return@forEach,
                    ipAddress = ev.ipAddress,
                    userAgent = ev.userAgent,
                    details = ev.details,
                    createdAt = Instant.ofEpochSecond(ev.createdAt),
                ),
            )
        }

        return ImportSummary(
            newTenantSlug = newSlug,
            users = export.users.size,
            applications = export.applications.size,
            roles = export.roles.size,
            groups = export.groups.size,
            claimMappers = export.claimMappers.size,
            socialProviders = export.socialProviders.size,
            signingKeys = export.signingKeys?.size ?: 0,
            auditEvents = export.auditLog?.size ?: 0,
        )
    }

    private fun lookupRoleId(
        name: String,
        rolePkByName: Map<RoleScopedKey, RoleId>,
    ): RoleId {
        val (clientId, plainName) =
            if (name.contains('/')) {
                val parts = name.split('/', limit = 2)
                parts[0] to parts[1]
            } else {
                null to name
            }
        return rolePkByName.entries
            .firstOrNull {
                it.key.name == plainName && it.key.clientId == clientId
            }?.value
            ?: error("Role reference '$name' could not be resolved within this export")
    }

    private fun parseRequiredAction(raw: String): RequiredAction? =
        runCatching { RequiredAction.valueOf(raw) }.getOrNull()

    /**
     * Returns groups in an order that guarantees every parent is processed before
     * its children. Catches cycles and missing parents up front so the inner write
     * loop never has to recover.
     */
    private fun topologicalGroups(groups: List<GroupBackup>): List<GroupBackup> {
        val byPath: Map<String, GroupBackup> =
            groups.associateBy { gb ->
                if (gb.parentGroupPath == null) gb.name else "${gb.parentGroupPath}/${gb.name}"
            }
        val visited = mutableSetOf<String>()
        val result = mutableListOf<GroupBackup>()

        fun visit(
            path: String,
            stack: Set<String>,
        ) {
            if (path in visited) return
            check(path !in stack) { "Group hierarchy contains a cycle including '$path'" }
            val gb = byPath[path] ?: error("Group path '$path' referenced but not present in export")
            val parentPath = gb.parentGroupPath
            if (parentPath != null) visit(parentPath, stack + path)
            visited += path
            result += gb
        }
        byPath.keys.forEach { visit(it, emptySet()) }
        return result
    }

    private data class RoleScopedKey(
        val name: String,
        val scope: RoleScope,
        val clientId: String?,
    )
}

/**
 * Lightweight summary returned after a successful import. The CLI prints it,
 * the route layer renders it in the admin UI confirmation page, and the future
 * MCP tool will return it as the structured response.
 */
data class ImportSummary(
    val newTenantSlug: String,
    val users: Int,
    val applications: Int,
    val roles: Int,
    val groups: Int,
    val claimMappers: Int,
    val socialProviders: Int,
    val signingKeys: Int,
    val auditEvents: Int,
)
