package com.kauth.adapter.web

import java.util.Properties

/**
 * Build-time application metadata exposed to server-rendered web views.
 *
 * The values come from version.properties when available and fall back to
 * sensible defaults for local IDE runs.
 */
data class AppInfo(
    val version: String = "dev",
    val kotlinVersion: String = KotlinVersion.CURRENT.toString(),
    val ktorVersion: String = "unknown",
) {
    companion object {
        /**
         * Cache-busting query string for static assets (CSS/JS).
         * Set once at startup from [loadAppInfo]; read by all View files.
         */
        @Volatile
        var assetVersion: String = "dev"
            internal set
    }
}

/**
 * Loads build-time metadata from the version.properties resource generated by
 * the generateVersionProperties Gradle task.
 *
 * Falls back to sensible defaults when the file is absent, for example when
 * running directly from the IDE without first executing the Gradle task.
 */
fun loadAppInfo(): AppInfo {
    val props = Properties()
    AppInfo::class.java.classLoader
        ?.getResourceAsStream("version.properties")
        ?.use { props.load(it) }
    val info =
        AppInfo(
            version = props.getProperty("app.version", "dev"),
            kotlinVersion = props.getProperty("kotlin.version", KotlinVersion.CURRENT.toString()),
            ktorVersion = props.getProperty("ktor.version", "unknown"),
        )
    AppInfo.assetVersion = info.version
    return info
}
